# Generated by Django 4.2.2 on 2023-07-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('info', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
    ]
