# Generated by Django 4.2.2 on 2023-08-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('doctorName', models.CharField(max_length=30)),
                ('ahvol', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('belgilar', models.TextField()),
                ('boshlangan', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
