# Generated by Django 4.2.2 on 2023-08-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_register_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
