# Generated by Django 4.2.2 on 2023-08-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='', verbose_name='media/rasmlar')),
            ],
        ),
    ]
