# Generated by Django 4.2.2 on 2023-08-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rasm',
            field=models.ImageField(upload_to='', verbose_name='/rasmlar'),
        ),
    ]
