# Generated by Django 4.2.2 on 2023-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_image_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='rasm',
            field=models.ImageField(upload_to='rasmlar'),
        ),
    ]
