# Generated by Django 4.2.2 on 2023-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('muallif', models.CharField(max_length=30)),
                ('narxi', models.FloatField()),
                ('miqdor', models.IntegerField()),
            ],
        ),
    ]
